SET ECHO ON

SELECT 
	COURSE_NO
   ,SECTION_ID
   ,START_DATE_TIME
FROM 
	SECTION
SET SPOOL OFF

SPOOL %SQL-OUTPUT%\Query5.2.txt
SELECT 
	COURSE_NO
   ,SECTION_ID
   ,to_Char(START_DATE_TIME, 'Dy, Month DD')
FROM 
	SECTION

SELECT 
	COURSE_NO
   ,SECTION_ID
   ,to_Char(START_DATE_TIME, 'Dy, Month DD')
FROM 
	SECTION
WHERE 
	to_Char(START_DATE_TIME, 'Dy') = 'Jue'