REM DESPLEGAR EL NUMERO DE TUPLAS DE COURSE
REM DESPLEGAR EL NUMERO DE TUPLAS DE SECTION
REM DESPLEGAR EL NUMERO DE TUPLAS DEL  PRODUCTO CARTESIANO
REM DESPLEAGR EL NUMERO DE ATRIBUTOS DE COURSE A PARTIR DEL DICCIONARIO DE DATOS
REM DESPLEAGR EL NUMERO DE ATRIBUTOS DE COURSE A PARTIR DEL DICCIONARIO DE DATOS
REM CONSULTANDO LA TABLA USER_OBJECTS
REM CONSULTANDO LA TABLA USER_TAB_COLUMNS
SELECT COUNT(*) FROM COURSE;
SELECT COUNT(*) FROM INSTRUCTOR;
SELECT COUNT(*) FROM COURSE, INSTRUCTOR;
DESC USER_OBJECTS;
DESC USER_TAB_COLUMNS
SELECT DISTINCT OBJECT_TYPE FROM USER_OBJECTS;
COL DT FORMAT A28
SELECT DISTINCT DATA_TYPE DT FROM USER_TAB_COLUMNS;
REM DESPLEGAR NOMBRE DE TABLA, NOMBRE DE COLUMNA, TIPO DE DATO LONG DE DATO Y PRECISION
COL TN FORMAT A10
COL CN FORMAT A18
COL DT FORMAT A10
COL DL FORMAT 999
COL DP FORMAT 999
COL NU FORMAT A10
SELECT TABLE_NAME    TN
	, COLUMN_NAME    CN
	, DATA_TYPE      DT
	, DATA_LENGTH 	 DL 
	, DATA_PRECISION DP
	, NULLABLE       NU
	FROM USER_TAB_COLUMNS
	WHERE TABLE_NAME = 'COURSE'
		OR TABLE_NAME = 'INSTRUCTOR';
COLUMN TN FORMAT A28		
SELECT DISTINCT TABLE_NAME TN FROM USER_TAB_COLUMNS
	ORDER BY 1;		
REM DESPLEGAR EL CURSO, LE GRUPO O SECCION LA DESCRIPCCION, LA SEDE  O LOCALIZACION
REM Y EL IDENTIFICADOR DEL INSTRUCTOR
COL RN FORMAT 999
COL CC FORMAT 999
COL SS FORMAT 999
COL CD FORMAT A28
COL SL FORMAT A10
COL SI FORMAT 999
SELECT ROWNUM RN,c.course_no CC	, s.section_no SS	, c.description CD
	, s.location SL 
	, s.instructor_id SI
FROM course c, section s
WHERE c.course_no = s.course_no;