spool q7_14_febrero.txt
PROMPT DESPLIEGA LOS ATRIBUTOS ID, NOMBRE DE DEPTO, MANAGER Y UBICACION
COLUMN Num FORMAT 9999
COLUMN Nombre|depto format A21
COLUMN GERENTE FORMAT 9999
COLUMN LUGAR FORMAT 9999
SELECT DEPARTMENT_ID "Num", DEPARTMENT_NAME "Nombre|depto|",
	MANAGER_ID GERENTE,LOCATION_ID LUGAR
FROM DEPARTMENTS
WHERE MANAGER_ID IS NOT NULL
ORDER BY 2;
spool off